### ISSUE TITLE
ipad problems

### ISSUE THREAD

**Issue by kasper21** [websanova/wPaint#10]
Hi there,

I´m testing the new version with mobile support on my iPad. I setup a test site here: http://rvw.bespokestudio.com/test/

There seems to be a bug on iPad. It seems to sometimes use 0/0 position instead of last touched coordinates.

Would be great if you can look at it.

thank you!

![photo 1 ](https://f.cloud.github.com/assets/588803/38701/1534c99e-54fc-11e2-8585-c8a03d322e57.jpg)

**Comment by kasper21** [comment]
also, even all the elements are positioned fixed with 100% height and width and overflow:hidden. I had to use $(document).bind(
'touchmove',
function(e) {
e.preventDefault();
}
);
to disable elastic scroll and enable drawing. could this be integrated so the scroll event is prevented when touching over canvas?

**Comment by websanova** [comment]
Hey Kasper,

Thanks, I will take a look at it sometime this week.

**Comment by kasper21** [comment]
thank you!

**Comment by websanova** [comment]
Okay, so first issue, I was able to see the issues you were having on my ipad, but couldn't really figure out why it was behaving that way.  I setup a fullscreen.html demo that seems to work okay with my ipad, hopefully that will help out a bit, I'll leave the ticket open for now.

As for the other issue, with the "touchmove", I resolved it under another issue here (https://github.com/websanova/wPaint/issues/5)

**Comment by websanova** [comment]
Old issue, I want to close this out.  If you're still using the plugin, try upgrading to the new 2.0 version.

**Comment by ketanvekariya** [comment]
IPAD issue: 
=======
Clicking on one of the icons gives you the specific tool

But when you want to change it to another, the previous one still remains activated

As if it is still being clicked

So in order to overwrite it, you have to click 2 times on the new tool you want to you


@websanova  why ipad require 2 click to change the control. Can you please help me for figure out.
