### ISSUE TITLE
Having trouble "uploading' image to server folder

### ISSUE THREAD

**Issue by tkcool** [websanova/wPaint#12]
Hi,  I am having some trouble uploading the image to the server, the was folder created as per examples. all permissions are all set.  I can't work out why it does not post the image.

I have set it to upload in the same directory as where the load images are located.

Any help will be appreciated to get this working,

function upload_image(id)
        {
            var imageData = $("#" + id).wPaint("image");

```
        $.ajax({
            url: '/images/demo/upload.php',
            data: {image: imageData},
            type: 'post',
            success: function(resp)
            {
                alert('successfully uploaded image!');
            }
        });
```

**Comment by websanova** [comment]
Okay, if you do a `console.log(resp)` in your success function what do you
get?

**Comment by websanova** [comment]
Hey, are you still having issues with this or were you able to resolve?
