### ISSUE TITLE
Definition/Translation of buttons tips

### ISSUE THREAD

**Issue by demonslord** [websanova/wPaint#13]
At the moment, we can not change the tip / title of buttons, because they are fixed in javascript code.

I propose to make it configurable:
- Create properties for this
- Or create template translation, like in jquery ui datepicker.

If you need more clarifications, please contact.

Best Regards.
Alexander Bulei

**Comment by demonslord** [comment]
Closed? Why? :(

**Comment by websanova** [comment]
Seemed like there was just a conversation going on with this issue, not an actual issue posted.  If you have an issue please repost (or edit this issue) something more clearly with a specific bug or feature you would like to see.

**Comment by demonslord** [comment]
updated.

**Comment by websanova** [comment]
Okay, now I understand, thanks for the clarification.  I'll add an option for this tonight, it will only take me a few minutes.

**Comment by demonslord** [comment]
Good :)

Thanks.

**Comment by websanova** [comment]
Okay `menuTitles` option added for this, just check the readme, you can overwrite any of the defaults.

**Comment by demonslord** [comment]
Nice. thanks.
