### ISSUE TITLE
Undo Redo not working with jquery 3x

### ISSUE THREAD

**Issue by mirasyediler** [websanova/wPaint#130]
Hello,

There are incompatibilities with jquery 3x. Undo and Redo functions do not work. Can you help me.

**Comment by hamouda-saadi** [comment]
> Hello,
> 
> There are incompatibilities with jquery 3x. Undo and Redo functions do not work. Can you help me.

Use src/wPaint.js and src/wPaint.utils.js and update $(myImage).load(loadImage); => $(myImage).on("load", loadImage).trigger( "load" );  L 225

**Comment by mirasyediler** [comment]
> > Hello,
> > There are incompatibilities with jquery 3x. Undo and Redo functions do not work. Can you help me.
> 
> Use src/wPaint.js and src/wPaint.utils.js and update $(myImage).load(loadImage); => $(myImage).on("load", loadImage).trigger( "load" ); L 225

Thank very much.
