### ISSUE TITLE
Add nicer icons

### ISSUE THREAD

**Issue by websanova** [websanova/wPaint#15]
The icons are ghetto, get a nicer look for it.

**Comment by kasper21** [comment]
Hey Websanova,

I did a cleaner version of the icons. How do you want me to send them to you?

Also, in return, a small question: I´m looking into pausing wpaint functions while using a magnifying glass and then unpause after usage of wpaint. any tip?

cheers

**Comment by websanova** [comment]
Hmm, well, o think you can just disable mouse down or set the divs to
disable or something.

Might have to add that in the future,.

Icons You can just email to me, that would be awesome.

Thnaks

**Comment by kasper21** [comment]
I didn´t do the bold underline and one other icon because I didn´t need
them. they´re png´s with transparent background.

let me know if you want me to make them and send it to you.

I´m not sure how to disable mouse down, .unbind maybe?

thanks,
Kasper

**Comment by avernet** [comment]
Are the new icons checked into the latest codebase? The tool works great, and after a while you forget the look of the icons (functionality is more important!), but I can see the look being can an initial turnoff for some people.

**Comment by websanova** [comment]
Someone did send me some, but I've been so busy I haven't had time to look
into it, will try to do it soon.

**Comment by kasper21** [comment]
Hey avernet, i could send them to you if you want to replace them yourself.

**Comment by websanova** [comment]
ya, that might be best for now, I will have to add some themeing options to
make this easier.  I'm just wrapping up an update with the blog and plugins
pages, so I will be working on this plugin in the near future.

**Comment by avernet** [comment]
@kasper21 Certainly, feel free to email me directly (avernet AT scdi DOT org).

**Comment by SpecialtyLEDSConstruction** [comment]
Could I get those too please?  specialtyleds AT gmail DOT com

**Comment by avernet** [comment]
@kasper21 I am not sure if you still have those icons around, but it would be great if you could share them with the community when you get a chance. If it is images, you can just drag and drop them in a response here, and they will be attached to your comment.

**Comment by kasper21** [comment]
hey guys,

here the icons:

![icon_bold](https://f.cloud.github.com/assets/588803/891142/856451d6-fa4b-11e2-8407-f634356308bd.png)
![icon_clear](https://f.cloud.github.com/assets/588803/891143/857cefd4-fa4b-11e2-97a6-0df849ea0f1a.png)
![icon_down](https://f.cloud.github.com/assets/588803/891144/85921bfc-fa4b-11e2-8fbf-b31c65f157a6.png)
![icon_ellipse](https://f.cloud.github.com/assets/588803/891145/8594e152-fa4b-11e2-847e-2a3126ff8524.png)
![icon_italic](https://f.cloud.github.com/assets/588803/891147/8598dd02-fa4b-11e2-86cf-f734a09fff60.png)
![icon_eraser](https://f.cloud.github.com/assets/588803/891146/85968174-fa4b-11e2-95d7-1d32cbff4661.png)
![icon_line](https://f.cloud.github.com/assets/588803/891148/859d83ac-fa4b-11e2-94a1-f9b49dbdf093.png)
![icon_pencil](https://f.cloud.github.com/assets/588803/891149/859f2a36-fa4b-11e2-9262-db0b7de80f40.png)
![icon_rectangle](https://f.cloud.github.com/assets/588803/891150/85ab0df6-fa4b-11e2-9738-95e633f71518.png)
![icon_redo](https://f.cloud.github.com/assets/588803/891151/85aa4560-fa4b-11e2-8723-db7fc97a1a6c.png)
![icon_text](https://f.cloud.github.com/assets/588803/891152/85ad2988-fa4b-11e2-9c0d-73d0d6451164.png)
![icon_underline](https://f.cloud.github.com/assets/588803/891153/85af78fa-fa4b-11e2-8eeb-182d5f9eddcb.png)
![icon_undo](https://f.cloud.github.com/assets/588803/891154/85b42134-fa4b-11e2-9d00-3e5e14925b27.png)

**Comment by avernet** [comment]
@kasper21 Excellent, I used those icons in our app, thank you.
