### ISSUE TITLE
Downloading the Image

### ISSUE THREAD

**Issue by hiteshsingla** [websanova/wPaint#16]
Hi!!
I want to download the drawing done by user on the client side..
Glad if i get some help on this.
Thank You.

**Comment by websanova** [comment]
There is an example in the index.html file that uses upload.php.  Try that, if you have specific issues let me know.

**Comment by hiteshsingla** [comment]
thank you..
can i get some help over how to email the image?

**Comment by hiteshsingla** [comment]
I am using a jquery FancyBox and want to use wpain in that pop up..is this possible??

**Comment by websanova** [comment]
Well, with emailing the image, that is just sending an email with whatever backend language you are using..  As far as FancyBox goes, wPaint works on any div container you assign it to, how you set it up or arrange it within your site is up to you.  I would assume you could load up some generic `<div id="wPaint"></div>` container into fancybox and then run it that way.

Anyway, these seem like general coding questions, and are not related to issues with wPaint, For your questions I would suggest asking on stackoverflow.
