### ISSUE TITLE
Add moveable symbols 

### ISSUE THREAD

**Issue by bnowacky** [websanova/wPaint#17]
I wanted to extend the plugin to add symbols to the canvas using something like raphael or jcavas. Would be a symbol icon, which spawns a new menu (similar to text menu), with a list of the sympols. Symbols would get passed as parameters similar to offsets=X, offsetY... array of paths for the images you wanted to include...

I've got the icon in the menu, but I'm having trouble following the code as to where I would attach an action to the button click... Any suggestions or guidance is appreciated !

**Comment by websanova** [comment]
I'll look into creating a separate menu for this (like the text one) this weekend.  I can make the symbols an optional setting so that you developers can set their own symbols in some kind of array or something

**Comment by asif-javed** [comment]
any update regarding this ?

**Comment by websanova** [comment]
Sorry, been busy with things at work and haven't had a chance to get on top
of this yet.  leaving the country in a few weeks so not sure when I'll get
a chance to work on it.

**Comment by malik777** [comment]
any update?

**Comment by bnowacky** [comment]
Creating a symbols menu wasn't difficult to do.... The problem is making it 'moveable'. As mentioned in #35, you can't easily make them moveable. Usual logic for moving is to redraw the image with every mouse move, which would clear the canvas. Couple of solutions are to implement a layers approach (similar to kineticjs or canvas).

I was able to make this work, but it was a bit of a hack. I css'd my canvas that's created with websanova with a z-index of 4500. Then when I clicked an image, I used jquery UI to make the images draggable, and actually created new image nodes in the DOM with a z-index higher than the canvas. This allowed me to move images around the screen, It was a short-term hack though, as everything is not contained in the canvas.
