### ISSUE TITLE
cannot clear after textbox

### ISSUE THREAD

**Issue by kongaraju** [websanova/wPaint#18]
create a text then. the only text clearing not the whole textbox.

**Comment by websanova** [comment]
Not sure what you mean here.  If you add text into the textbox and click somewhere else after you're done what happens?

**Comment by kongaraju** [comment]
instead of somewhere else click I clicked on clear still the box is on the view.

**Comment by websanova** [comment]
okay, try clicking somewhere else on the canvas...or switching to a different icon.
