### ISSUE TITLE
how can i draw from code?

### ISSUE THREAD

**Issue by kongaraju** [websanova/wPaint#19]

**Comment by websanova** [comment]
Do you mean, how can you insert an existing image as a background?

**Comment by kongaraju** [comment]
not background I would like to override paint object?
and redraw with new paint object.

**Comment by bvempalli1986** [comment]
your question is how to erase the previous drawing and paint fresh? if this is not you are expecting. please explain in detail. i may have come across this problem.

**Comment by kongaraju** [comment]
yah that is my question

**Comment by bvempalli1986** [comment]
there are two ways 
1. use cross mark in the menu given for drawing.
2. use $("#wPaint").wPaint("clear");
check the code of the demo which is available that will give you most of the answers. hope this helps.

**Comment by kongaraju** [comment]
I would like to draw with my new paint object programmatically . I can clear paint as you suggested.

**Comment by bvempalli1986** [comment]
the question you provided is not clear to me. can you please explain in full, with an example if you can.

**Comment by kongaraju** [comment]
my context:
when user draw a line,  
I need to send paint line object to server then 
server broadcast it to other users,
when client receives paint object I need to redraw the paint.

**Comment by bvempalli1986** [comment]
$("#wPaint").wPaint("image"); will give the image you have drawn. send this image to your client and keep this image as back ground. activate the paint again $("#wPaint").wPaint();

**Comment by kongaraju** [comment]
in that case how undo or clear works with image.

Benfits with sending paint object and drawing with paint object.
1. every one can update others view.
2. then can propose new view.

using images disadvantages:
1.large size.
2. http requests
etc..

**Comment by bvempalli1986** [comment]
it is a good question. but i am sorry i don't know the answer. but if you get the answer in your research please let me know. i have to do similar functionality(modifying the image) in my road map. and i will let you know if i know any thing.

**Comment by websanova** [comment]
You can get and set an image using:

```
var imageData = $('#elem').wPaint('image');
$('#elem2').wPaint('image', imageData);
```

You can also just set an image path:

```
$('#elem2').wPaint('image', '/path/to/file.jpg');
```

For anything about synching between two clients on different browsers that becomes an issue outside of wPaint as you would need to look into polling the server for changes or using sockets.
