### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FernandoI7** [websanova/wPaint#2]
How can I save the drawing in binary format to put it in the database?

**Comment by websanova** [comment]
var imageData = $("#wPaint3").wPaint("image");
$("#canvasImage").attr("src", imageData);

or just send the data to your server and save it as a png.

Rob

On Fri, Aug 3, 2012 at 3:42 PM, FernandoI7 <
reply@reply.github.com

**Comment by FernandoI7** [comment]
This is my situation:
I have three fields to record the image in the database. One is the image that is in the form bytea. The second is the name of the file to be saved. And the third is the extension. But this code:

var imageData = $ ("# wPaint3"). wPaint ("image");
$ ("# canvasImage.") attr ("src", imageData);

Just save the image in base64 format. I need the value that is in the input tag is the same as if I had attached the image of my computer, so I can store it in the field bytea.

**Comment by websanova** [comment]
Right, so send the base64 data to your server and convert it to whatever
you like and save it. ;)

Rob

On Mon, Aug 6, 2012 at 2:38 PM, FernandoI7 <
reply@reply.github.com

**Comment by FernandoI7** [comment]
I managed to save bytea format image but the image is only retrieved if it is shaped base 64 otherwise unable to retrieve the bytea and display the image.

**Comment by FernandoI7** [comment]
Finally got everything I needed, but I had to work with the image always in base64 format and saves it as bytea. It worked and that's what matters! Thanks for the help.
