### ISSUE TITLE
remove and add paint functionality

### ISSUE THREAD

**Issue by bvempalli1986** [websanova/wPaint#20]
did you have any thing to remove all the functionality after paint once i am done. And load it when i need it. like removepaint button remove whole functionality or addpaint for adding whole paint functionality back when needed. Please let me know as soon as possible so that i can use it in my demo.

**Comment by websanova** [comment]
Well there is the "x" icon that clears the image.  You can add/remove this icon through the options.  doing it in real time is not possible through the plugin, but each icon has it's own class, so you can remove it with some simple javascript.

`$('._wPaint_clear').toggle();` 

Or something like that.

**Comment by bvempalli1986** [comment]
let me briefly explain you about the application that i am doing. In my application i need to drag an object on to another image or canvas and rotate, drag, resize that object as and when it is needed(this i already done). but when i am integrating with paint application once i start the paint using $("#wpaint").wPaint(); . i could not move the object rotate the object because the mouser pointer is holding the control of the paint. i tryed use $('._wPaint_menu').remove(); which is removing the menu but the paint is still on. i also tryed to use $('._wPaint_clear').toggle(); but it is giving toggle effect to the menu but not removing the paint functnality from there. if you know the solution to disable and enable the paint that should remove the paint funtionalty but not the paint i drawn already. or if you think of any other solution that would make my drag and rotate work. That would be great help of you.

**Comment by websanova** [comment]
I'm still not really getting it, you want to disable the whole paint
canvas?  If that's the case, the option is not in there, but popping a
transparent div on top would do the trick as a work around.

**Comment by bvempalli1986** [comment]
my question is how to retain the old functionality like rotate, drag to a dropped object after the painting the canvas.

**Comment by websanova** [comment]
Well, wPaint does not have any rotate functionality.  I'm not sure what
you're talking about now.

**Comment by bvempalli1986** [comment]
i know that i have that drag, drop , re size, rotate functionality already built in my application. but when i integrate the paint application once the drag,drop, rotate functionality that were in my application are now working.

**Comment by websanova** [comment]
How are you initializing wPaint?

**Comment by bvempalli1986** [comment]
i got some success by saving the div content in one temp variable and  removing the canvas from the div and replacing the the div original value with canvas as and when i need paint. But the drawing that i used previously is gone. can you tell me where is the paint data saving/recording when i use your plug in.

**Comment by websanova** [comment]
https://github.com/websanova/wPaint#wpaintjs

**Comment by bvempalli1986** [comment]
thank you for the response i got the answer.

<div id="wPaint"></div>

<img id="canvasImage" src=""/>

<script type="text/javascript">
    var imageData = $("#wPaint").wPaint("image");
    $("#canvasImage").attr('src', imageData);
</script>
