### ISSUE TITLE
Cannot save image on android chrome

### ISSUE THREAD

**Issue by davidsoderstrom** [websanova/wPaint#23]
Hi!
Last time i tried painting on my chrome android device was a few months ago. I set up wPaint and could do just fine within minutes, so thats great. However I couldnt save the image on Chrome for Android. The save option was greyed out when I tried back then. I could open the image in both the other options. 

I tried it today, and some of the latest updates made it possible to atleast click the option to save, but it doesnt do anything? Or have i missed anything? It doesnt save the image to the device when I hold my finger to get the menu and hit save. 

By design, or a bug?

Regards,
David

**Comment by websanova** [comment]
Are you referring to any specific demo?  The plugin itself doesn't have any
save options.  The drawing are in a canvas, so I don't think there is any
actual "image" yet, other than maybe setting a background.

**Comment by davidsoderstrom** [comment]
Just the feature where you render a png that you later could either right click and save as, or hold finger > save. Should be possible yeah?

**Comment by websanova** [comment]
Do you mean when you set as image using imageBg or image?

**Comment by davidsoderstrom** [comment]
using saveImage(), as in your example

**Comment by websanova** [comment]
Okay,

Well, I don't ever remember having that saveImage link/button greyed out.
 Just checked it now and it seems the image is there, and you can
click/view it in another tab.

The save image part has actually nothing to do with the plugin, it's just
extra code around the plugin, so any updates wouldn't be related to that.
 If there is an issue with right clicking on the image it's probably
because another div element is overlaid on top of it somewhere.  That could
explain why it's working for you in some areas and not others.

**Comment by davidsoderstrom** [comment]
Yeah, the latest versions have fixed the greyed out button, but i still cant save it (it just doesnt download in on any of my andriod devices using chrome). I can see the image and open on new tab just fine though.

**Comment by websanova** [comment]
Right well, the "saveImage" button there is not really a save image,
perhaps that is a bit misleading, it's just loading the image into an <img>
tag.  If you want to save that image, just right click the image afterwards
and hit "save image" from the dropdown, but that's at the discretion of the
browser you are using.

**Comment by davidsoderstrom** [comment]
Yeah, thats my problem. I can get the image showing just fine, but when I hit that "save image" when holding my finger a longer time on an android device it doesn't download it. Nothing happens. Is it just my android devices with google chrome? Does it work for others? Right clicking on a windows pc works just fine though, it saves the .png with no problems.

**Comment by websanova** [comment]
Ya, I would have to think that is a device issue, can you have images from
other websites?

**Comment by davidsoderstrom** [comment]
Yeah, thats the only reason. But OK, then I know it's something I can figure out by myself. 

If I just can ask my followup question though. Are there any way to name the image that I download? As it is now it just says some generic (in swedish) download.png. Can I rename it to some variable I can manipulate?

**Comment by websanova** [comment]
Closing out this issue.  If you're still using plugin, try upgrading to 2.0 version.
