### ISSUE TITLE
draw data

### ISSUE THREAD

**Issue by ch60234** [websanova/wPaint#26]
Can I save draw data like x,y axis array or any data type ?(not image)
I want reload draw data from database,and make it editable and save.
can it possible ?

**Comment by websanova** [comment]
`var imageData = $("#wPaint").wPaint("image");`  will give you a base64 encoded string.

**Comment by ch60234** [comment]
if I get the draw data string like "data:image/png;base64,......."
how can I load this data?
var imgData = "data:image/png;base64,......"
$("#wPaint").wPaint("image", imgData);

ike this?
I try this but doesn't work.

**Comment by ch60234** [comment]
sorry,it doesn't work maybe I set background,

**Comment by websanova** [comment]
Hmm, well have you tried other images, other png strings, maybe the one
from the demo?

**Comment by websanova** [comment]
I just upgraded to wPaint 2.0, see if the issue still persists there, otherwise I want to close out all outstanding tickets.
