### ISSUE TITLE
How can I get the (centerX,centerY) of the ellipse?

### ISSUE THREAD

**Issue by femosso** [websanova/wPaint#29]
I'm trying to pass all the shapes I've drawn in my Web application to an Android application. For this I have to get some shapes coordinates. I've already done it for lines and rectangles, but how can I get the coordinates from an ellipse? Specially the center of it

Thanks!

**Comment by websanova** [comment]
Well, I would guess that you could do whatever you did for the other shapes
and just divide the width and height by two to get the center.

**Comment by websanova** [comment]
Assuming you got this working and closing out this issue.
