### ISSUE TITLE
Drawing circles instead of ellipses

### ISSUE THREAD

**Issue by femosso** [websanova/wPaint#30]
How can I only let user draw circles instead of ellipses?

I've tried to change this:

_self.ctxTemp.beginPath();
_self.ctxTemp.moveTo(e.x, ym);
_self.ctxTemp.bezierCurveTo(e.x, ym - oy, xm - ox, e.y, xm, e.y);
_self.ctxTemp.bezierCurveTo(xm + ox, e.y, xe, ym - oy, xe, ym);
_self.ctxTemp.bezierCurveTo(xe, ym + oy, xm + ox, ye, xm, ye);
_self.ctxTemp.bezierCurveTo(xm - ox, ye, e.x, ym + oy, e.x, ym);
_self.ctxTemp.closePath();
if(_self.settings.lineWidth > 0)_self.ctxTemp.stroke();
_self.ctxTemp.fill();

in drawEllipseMove() function

To this:

_self.ctxTemp.beginPath();
_self.ctxTemp.arc(aux1, aux2, r, 0, 2 \* 3,14, false);
_self.ctxTemp.closePath();
_self.ctxTemp.fill();

Where aux1 and aux2 are center X and Y of the circle and r is the radius. But it doesn't draw anything. What can I change?

**Comment by websanova** [comment]
Added in wPaint 2.0, please upgrade.
