### ISSUE TITLE
draw data

### ISSUE THREAD

**Issue by kongaraju** [websanova/wPaint#31]
https://gist.github.com/kongaraju/5394641

I just added new method draw data but It is not functioning as expected. 

I am using drawdown, drawmove, drawup to send data then using draw data method to draw.

But some data missing at the end and beginning, Is there anything wrong in my approach.

and drawing shape is also mysterious, I confused on taking event object and I just passing pageX and PageY.

I think that is major wrong step. may be I need to calculate the position.

**Comment by websanova** [comment]
Try upgrading to version 2.0 and see if you still get this issue, otherwise I want to close out any outstanding tickets
