### ISSUE TITLE
Resizable Canvas

### ISSUE THREAD

**Issue by saisurya** [websanova/wPaint#32]
Thank you for excellent work. I'm trying to make the canvas resizable. I tried to use .resizable() which is part of jQuery UI and no luck (I presume wPaint using jQuery UI from the JS imports).

Please advice possible way to make the canvas resizable.

Thanks & Regards,
Sai Surya.

**Comment by websanova** [comment]
Resizing is not possible with the plugin right now.  Resizing the canvas
object causes it to refresh.

**Comment by saisurya** [comment]
Oh ok! I added jQuery UI library and made $("#canvas").resizable(). This is just for my project only. However, the when I save the image, the image is captured is fixed size not the resized canvas. I'll figure out. Thanks again!

**Comment by websanova** [comment]
There is a new 2.0 version of wPaint just released that now contains a resize function, you can check the fullscreen demo in `test/fullscreen.html`
