### ISSUE TITLE
Unable to draw line as expected position

### ISSUE THREAD

**Issue by shimpeiT** [websanova/wPaint#34]
Hi,

I'm using IE10 on Win7 and cannot draw line as expected position.
Same problem also occurs on following demo site
(occurs on middle & last canvas, and does not occur on first one).
http://www.websanova.com/plugins/paint#websanova

In addition, 
- It looks this problem does not occur on Chrome v26 and Firefox v20.
- When setting browser's display scale of IE10 from 100% to 125%, this problem disappears. 
  (However, on other browser, always does not occur regardless of display scale...)

It would be appreciated if you could help me(though i think this is bug).

Thanks and Regards,

**Comment by websanova** [comment]
I've update to a new version, see if that is still happening in wPaint 2.0.  If not I want to close this ticket out.
