### ISSUE TITLE
jQuery("#wPaint").wPaint("image") blank after drawing

### ISSUE THREAD

**Issue by kasper21** [websanova/wPaint#36]
Hey Websanova,

hope my icons work for you.

I have a strange problem that just started to happen out of nothing.

I draw on the wpaint canvas and then I try to retrieve the data with jQuery("#wPaint").wPaint("image"); and I get the data but it´s always a blank png.

help would really be appreciated.

cheers,
Kasper

**Comment by websanova** [comment]
What device/browser?

**Comment by kasper21** [comment]
osx 10.7.5 and chrome, latest version

**Comment by kasper21** [comment]
you can see a test page here: http://rvw.bespokestudio.com/test3/

**Comment by darshana-dholariya** [comment]
Hey Websanova,

I have a strange problem in chrome latest version of Windows 7.

When I can try to draw anything on wPaint canvas using pencil, rectangle,ellipse, line etc.. it only show when I drag
rectangle or else on wPaint canvas but not draw on canvas. I used wPaint with resize functionality including           

var imageData = $("#wPaint").wPaint("image"); // if you want to maintain the image after resizing the canvas

but there is not working in chrome in windows 7.

Above you mention URL : http://rvw.bespokestudio.com/test3/ it is working well  but when I resize window the canvas is not resize so it's working well in my problem when I resize window my canvas is set new width and height.

I also download latest version of wPaint-master and I test index.html file in my chrome. it's working well and I also test fullscreen.html file. it's also working welll when resizing window but canvas image data is not maintain when window resize and I remove comment from these two lines.

var imageData = $("#wPaint").wPaint("image"); // if you want to maintain the image after resizing the canvas
$("#wPaint").wPaint("image", imageData);

and I test fullscreen.html file. it's not working when resizing window with image data maintain. nothing is draw on canvas when I remove comment from those lines.

Here is link to check my wPaint : http://www.stridedev.com/test.php?ddalessio=1
go to this link and click on notebook type icon below calculator icon.
please visit and check.

Please give me some solution to solve this issue.

Regards,
Darshana

**Comment by websanova** [comment]
Hey Darshana,

Ok, I've added a `resize` function,t you can call it using
`$('#wPaint').wPaint('resize');`

Just grab the latest version there is an updated example in
`test/fullscreen.html`

See if that helps.

Rob

**Comment by darshana-dholariya** [comment]
Hey Websanova,

I used `$('#wPaint').wPaint('resize');` but my problem is not solved.

Please check below link of video so you can see what is the problem.
http://screencast-o-matic.com/watch/cIQFi5VGrz

**Comment by websanova** [comment]
Seems like you're using the old version.  Try popping in the latest one.
