### ISSUE TITLE
Issue ColorPicker / jQuery Mobile

### ISSUE THREAD

**Issue by netwavetech** [websanova/wPaint#41]
There is a conflict with jQuery Mobile and the color picker.  When jQuery Mobile is included in the page,  the color picker will not show.  I have confirmed that the HTML is being changed to show, but it does not show.  

As soon as the jquery mobile js file is removed (can leave the css),  the color picker shows fine.

**Comment by websanova** [comment]
I want to close out any outstanding issues, wPaint 2.0 has been released can you upgrade and check if you're still getting these issues?
