### ISSUE TITLE
How to draw a straight line?

### ISSUE THREAD

**Issue by nadiamode** [websanova/wPaint#43]
I don't know where to set this option, I want to let user select to drawing a straight line or free hand

**Comment by websanova** [comment]
There are options in the menu to the right of the rectangle and circle for a line and pencil.  Line is for drawing straight lines and the pencil is for free hand draw.  If you do not see the icons, perhaps you have some bug that is not displaying them.  Check the demo online here http://wpaint.websanova.com to make sure the menu icons match up.

**Comment by nadiamode** [comment]
ok, i got it thank so much
