### ISSUE TITLE
Changing fillStyle by javascript?

### ISSUE THREAD

**Issue by davidsoderstrom** [websanova/wPaint#44]
Im doing > $("#wPaint").wPaint("red", "#ff0000") < in a javascript and it runs the following code that i appended in wPaint.js. 

...
... else if(option == 'red' && settings !== undefined) { alert(settings); }
...

How would I go about changing fillStyle (the fill color) to whatever settings is? I might be tired, but I just cant get it to change anything?

**Comment by websanova** [comment]
Did you try $('#wPaint').wPaint('fillStyle', 'red');

**Comment by davidsoderstrom** [comment]
Marvelous! Works like a charm! Must say i really like wPaint, keep up the good work :-)

**Comment by websanova** [comment]
Thanks, I'll have a 2.0 coming out next week with a ton of improvements :)
