### ISSUE TITLE
Cannot load the icons menu image and cursor image ?

### ISSUE THREAD

**Issue by jackchewfj** [websanova/wPaint#52]

**Comment by websanova** [comment]
Double check your path.  And also note some browsers do not support custom icons as images.

**Comment by jackchewfj** [comment]
Yes, I already check my path, and I even doesn't change a single piece of code on it, however, when i lauch dev,html. fullscreen,html, or index.html. It cannot display the image of menu icon ?

I read on this 

“path

If you are putting wPaint into a path other than root (most likely you will) then you will need to set the path option since the image and cursor icon paths are set in the JavaScript and not in CSS. This means we can not make them relative from the included file like we can in the CSS file but rather relative to the dispalying page. The default path is just the root folder / but a path can be set for wpaint.”

Is it relate to my issue ?

**Comment by websanova** [comment]
Do you get any errors in console for image paths not found?  If you do what
path does it show there?

**Comment by jackchewfj** [comment]
Yup, below is the error message after I check with Inspect Elements of google Chrome, i launched all the demos by using google chrome
Failed to load resource  file:///D:/plugins/main/img/icons-menu-main.png
Failed to load resource  file:///D:/plugins/file/img/icons-menu-main-file.png
Failed to load resource  file:///D:/plugins/text/img/icons-menu-text.png
Failed to load resource  file:///D:/plugins/main/img/cursor-pencil.png
Failed to load resource  file:///D:/plugins/shapes/img/icons-menu-main-shapes.png

**Comment by websanova** [comment]
Ok, ya.  You are setting via file path so maybe not correct.

**Comment by websanova** [comment]
Closing out this issue, assuming you got sorted out with correct paths.

**Comment by josephgayod** [comment]
same here...having problem when i downloaded the latest version... the header icons are not showing...why.... haveng change the codes
