### ISSUE TITLE
Path being incremented

### ISSUE THREAD

**Issue by fabiojpoli** [websanova/wPaint#54]
Each new instance of wPaint he is pushing the wrong path and ends up referencing the icons (in the first instance is correct):

GET http://localhost/Neolearn/wPaint/wPaint/plugins/main/img/icons-menu-main.png 404 (Not Found) jquery.js:7311
GET http://localhost/Neolearn/wPaint/wPaint/plugins/file/img/icons-menu-main-file.png 404 (Not Found) jquery.js:7311
GET http://localhost/Neolearn/wPaint/wPaint/plugins/text/img/icons-menu-text.png 404 (Not Found) jquery.js:7226
GET http://localhost/Neolearn/wPaint/wPaint/plugins/shapes/img/icons-menu-main-shapes.png 404 (Not Found) 

GET http://localhost/Neolearn/wPaint/wPaint/wPaint/plugins/main/img/icons-menu-main.png 404 (Not Found) jquery.js:7311
GET http://localhost/Neolearn/wPaint/wPaint/wPaint/plugins/file/img/icons-menu-main-file.png 404 (Not Found) jquery.js:7311
GET http://localhost/Neolearn/wPaint/wPaint/wPaint/plugins/text/img/icons-menu-text.png 404 (Not Found) jquery.js:7226
GET http://localhost/Neolearn/wPaint/wPaint/wPaint/plugins/shapes/img/icons-menu-main-shapes.png 404 (Not Found) 

...

I can define the path glbal to all instances?

**Comment by fabiojpoli** [comment]
In test, I create 2 paint, the secound set path invalid:

```
    $('#wPaint').wPaint({
      path: '/wPaint-2.1.2/',
      menuOffsetLeft: -35,
      menuOffsetTop: -50,
      saveImg: saveImg,
      loadImgBg: loadImgBg,
      loadImgFg: loadImgFg
    });

    $('#wPaint2').wPaint({
      path: '/wPaint-2.1.2/',
      menuOffsetLeft: -35,
      menuOffsetTop: -50,
      saveImg: saveImg,
      loadImgBg: loadImgBg,
      loadImgFg: loadImgFg
    });
```

![captura de tela 2013-10-25 as 10 11 42](https://f.cloud.github.com/assets/663908/1407492/ea168c5a-3d6e-11e3-8a0b-c42e34cfd140.png)

**Comment by fabiojpoli** [comment]
Nothing? Any?

**Comment by ghost** [comment]
Change line 574 of [wPaint.js](https://github.com/websanova/wPaint/blob/master/src/wPaint.js#L574)

from:
`menu.items[key].img = _this.wPaint.options.path + (menu.items[key].img || menu.img);`

to:
`menu.items[key].img = menu.items[key].img || (_this.wPaint.options.path + (menu.items[key].img || menu.img));`

**Comment by fabiojpoli** [comment]
Thanks

**Comment by nishikantyadav** [comment]
this will not solve all icons problem submenu icon paths of shapes are not coming correctly.Any other changes also required ?
