### ISSUE TITLE
How to set groups of rectangles?

### ISSUE THREAD

**Issue by enmonie** [websanova/wPaint#57]
I try to set a group of rectangles and similar forms (shapes label) but it's impossible for my. Can I help me:

This is my part of code error:

rectangle: {
        icon: 'activate',
        title: 'Rectangle',
        group: 'shapes',
        useRange: true,
        index: 3,
        callback: function () { this.setMode('rectangle'); }
      }

Help me please

**Comment by websanova** [comment]
If you want to just display the rectangle and ellipse icons then just remove the shapes plugin file.

Otherwise if, you just want to mod the rectangle alone, try:

```
rectangle: {
    icon: 'activate',
    title: 'Rectangle',
    index: 3,
    callback: function () { this.setMode('rectangle'); }
  }
```

Let me know if that helps at all.

**Comment by enmonie** [comment]
I would put in the rectangle button a list of other similar geometric shapes. In case that you press the button. you see a list with other shapes and the user can choose one of this list. You can see the shapes that are configured in the file wPaint.menu.main.shapes.js:

" (function ($) {
  var img = 'plugins/shapes/img/icons-menu-main-shapes.png';

  // extend menu
  $.extend(true, $.fn.wPaint.menus.main.items, {
    rectangle: {
      group: 'shapes'
    },
    roundedRect: {
      icon: 'activate',
      group: 'shapes',
      title: 'Rounded Rectangle',
      img: img,
      index: 0,
      callback: function () { this.setMode('roundedRect'); }
    },
    square: {
      icon: 'activate',
      group: 'shapes',
      title: 'Square',
      img: img,
      index: 1,
      callback: function () { this.setMode('square'); }
    },
    roundedSquare: {
      icon: 'activate',
      group: 'shapes',
      title: 'Rounded Square',
      img: img,
      index: 2,
      callback: function () { this.setMode('roundedSquare'); }
    },
    diamond: {
      icon: 'activate',
      group: 'shapes',
      title: 'Diamond',
      img: img,
      index: 4,
      callback: function () { this.setMode('diamond'); }
    }," 

thank in advance

**Comment by websanova** [comment]
ok, I'm not understanding exactly what the issue is.  You can just follow the format in the shapes.js file to add more shapes.  You can even do this in separate file.

**Comment by enmonie** [comment]
I solve this problem. I couldn't see the buttons in this list because I didn't hold the button.

thanks
