### ISSUE TITLE
How to Clean content but hold the background image

### ISSUE THREAD

**Issue by qupei** [websanova/wPaint#58]
set background image:

 $('#wPaint').wPaint({
          image: 'wpaint/bizhi.jpg'
 });  

when I use 
$('#wPaint').wPaint('clear')
to clean content ,the background image is missing~~~
how will I do ?
thank you and forgive my badlly English.

**Comment by websanova** [comment]
You need to use `bg` to set a permanent background.

$('#wPaint').wPaint({
    bg: 'wpaint/bizhi.jpg'
});

**Comment by qupei** [comment]
thanks very much
