### ISSUE TITLE
Internet Explorer 8

### ISSUE THREAD

**Issue by frodopopodo** [websanova/wPaint#6]
Hi,
first, i found a minor bug:
The function clearAll: function() ends with a comma which causes an js error  in the ie8. If i delete the comma, the error is gone and the ie8 shows the correct message:
"Browser does not support HTML5 canvas, please upgrade to a more modern browser.".

second:
any idea how to make te ie8 work with wPaint? I tried Googles Explorercanvas
http://code.google.com/p/explorercanvas/
but it didn't helP :-((

Thanks for help!
Manuel

PS: By the way: GREAT tool, good job !!

**Comment by websanova** [comment]
Fixed.
