### ISSUE TITLE
Load small image in bigger canvas

### ISSUE THREAD

**Issue by renanvs** [websanova/wPaint#70]
When I draw on a larger screen and load the paint on a small image, is right.

But when I draw on a small image and carry a larger picture it is not proportional

Can anyone help me?

The yellow works fine (large to small)

The green don't (small to large)

![3](https://f.cloud.github.com/assets/1186165/2019268/de658c02-881f-11e3-84d3-51d7afe6606a.png)
![2](https://f.cloud.github.com/assets/1186165/2019269/de67e4b6-881f-11e3-88a3-d2809140288f.png)
![1](https://f.cloud.github.com/assets/1186165/2019270/de6a1074-881f-11e3-9b9a-e0f5312a429d.png)
![4](https://f.cloud.github.com/assets/1186165/2019271/de6b4d72-881f-11e3-9422-b445c11086d5.png)

**Comment by websanova** [comment]
I don't understand what you mean.

**Comment by renanvs** [comment]
When a i draw something in a large image and save, after load in a small image my draw, works fine.

But, when i draw in small image and save, and load my draw in an image larger, the draw dont scale, still the same size, but the image that i want is large

**Comment by ghost** [comment]
Hi, he works with me, I think he's using an old version of the plugin. I'll talk to him and see what's happening. :stuck_out_tongue_winking_eye:

**Comment by Izikio** [comment]
Actually i think he's right..I have a similar problem where i need to scale the foreground based on the placeholder. It scales down correctly, but does not scale up.

The resize check has only been applied to the scale down code..

Ln 181: if (myImage.width > _this.width || myImage.height > _this.height)

**Comment by websanova** [comment]
Ya, that was on purpose, otherwise you would be stretching the image out.  I would prefer to not have that as the default.  If I have a small image it should just center.  I will add an option for this instead.

**Comment by websanova** [comment]
Just added use the option `imageStretch: true`.  Default is false.
