### ISSUE TITLE
How can i hide from the menu a certain tools 

### ISSUE THREAD

**Issue by aldus25** [websanova/wPaint#71]
How can i hide from the menu a certain tools i wont be using? just with styles?  and also how can i load a background and fill it with the bucket?

**Comment by aldus25** [comment]
i solve this by hiddign the elements with css and loading the image in uri format.

**Comment by gnujeremie** [comment]
I did this by using "delete jQuery.fn.wPaint.menus.main.items.bucket;" for exemple

**Comment by websanova** [comment]
Should work but need to make sure to do it after you include the plugin
