### ISSUE TITLE
How can i save whats in my canvas locally. I have this function, help please

### ISSUE THREAD

**Issue by aldus25** [websanova/wPaint#72]
I have to save whats in my canvas with this function but i can seem to correctly get de canvas var, check this out:

```
  var canvas = getElementById("wPaint");
  var ctx = canvas.getContext("2d");    
      document.getElementById("theimage").src = canvas.toDataURL();
}
```

**Comment by websanova** [comment]
Just do $('#wPaint').wPaint('image');

**Comment by aldus25** [comment]
you mean like this?:

var canvas = $('#wPaint').wPaint('image');
      var ctx = canvas.getContext("2d");  
          document.getElementById("theimage").src = canvas.toDataURL();

That doesnt work either

**Comment by aldus25** [comment]
how can i achieve to save an image, locally ( i dont want to load it, i just want to save it) i even tryied canvas2image.js

**Comment by aldus25** [comment]
please help me, i need to save whats on my canvas to any format jpg, png etc. i can give a contribution "gittip"

**Comment by websanova** [comment]
https://github.com/websanova/wPaint/blob/master/README.md#image-data

**Comment by websanova** [comment]
Cannot save an image locally as far as I know.  User can save it themselves
once loaded into an image.

**Comment by websanova** [comment]
You will need to upload to change formats and do it on your server.

**Comment by aldus25** [comment]
the "Get the image data:" trick did it.

you save my life. heres goes a contribution. btw great plugin

**Comment by websanova** [comment]
Cheers, thanks.
