### ISSUE TITLE
How can I change the menuOrientation dynamically?

### ISSUE THREAD

**Issue by ghost** [websanova/wPaint#74]
Hi, I use the plugin in a dynamic width container, and when the wPaint is resized, I need to change the menu orientation when the width is too small.

Is it possible to do something like this?
`$("#wPaint").wPaint("menuOrientation", new_orientation)`

**Comment by websanova** [comment]
Just added with the latest push, should work now:

```
$("#wPaint").wPaint("menuOrientation", "vertical")
$("#wPaint").wPaint("menuOrientation", "horizontal")
```

**Comment by ghost** [comment]
Great, thanks!
