### ISSUE TITLE
transparency effect

### ISSUE THREAD

**Issue by MaximilianoRicoTabo** [websanova/wPaint#79]
Hi guys !

I'm trying to get transparency effect on my clients draws, and I get it applying opacity : 0.4 css rule to .wPaint-canvas. Now I'm wonder if it there any chance to save the image with the css applied, cause I couldn't achieve that.

Any other tip to achieve this goal is welcome too.

Thanks

**Comment by websanova** [comment]
There is no support for transparency yet.  Doing it via css won't help you
unless you applied that transparency each time you displayed the image.

**Comment by MaximilianoRicoTabo** [comment]
@websanova Thank you for the quick answer. Any tip for modify code to achieve this ? Do you think I could do ? Accept pull request for this If I get it ?

Thanks again Maxi

**Comment by ghost** [comment]
I needed to do that in my project too, but only to one tool to work as a "text marker", I made a modification when the mode is set, to get the current color, and transform into rgba, and aplying to the text marker. If you want to change to every tool, you can do that only changing the setFilStyle/setStrokeStyle functions in your custom menu JS file.

``` javascript
setFillStyle : function(color) {
  var hexToRgb, rgbColor;

  // function that transforms hex value to RGB
  // and returns an object with r, g, b and rgb (all values separeted by commas)
  hexToRgb = function(hex) {
    var b, g, r, result, shorthandRegex;
    shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
    hex = hex.replace(shorthandRegex, function(m, r, g, b) {
      return r + r + g + g + b + b;
    });
    result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    if (result != null) {
      r = parseInt(result[1], 16);
      g = parseInt(result[2], 16);
      b = parseInt(result[3], 16);
      return result = {
        r: r,
        g: g,
        b: b,
        rgb: "" + r + ", " + g + ", " + b
      };
    } else {
      return null;
    }
  };

  // get the RGBColor from the hex value
  RGBColor = hexToRgb(color);
  // set the fillStyle with the RGB color as rgba the 0.5 is the opacity
  this.options.fillStyle = "rgba(" + RGBColor.rgb + ", 0.5)";
  return this._setColorPickerValue('fillStyle', color);
};
```

Note: This will set a color with transparency for every tool
Note 2: My code might be different from your source code, I made some changes to fulfill my project needs =)

Hope that helps.

**Comment by websanova** [comment]
thanks, I will probably create this as a separate tool to toggle on off
later.

**Comment by MaximilianoRicoTabo** [comment]
@jsgusmao, thank you very much for the answer. I tried your tip and found 2 things.

In the  return line should be return this.menus.all.main._setColorPickerValue('fillStyle', color) instead of return this._setColorPickerValue('fillStyle', color), I guess this is a versions issue. 

That was easy to change but despite that, and unfortunately, when I save the file the opacity goes out and I really need to keep it in the generated image. 

Thanks for you tip anyway

**Comment by websanova** [comment]
Ya, the cokirpicker might not be supporting that.

**Comment by ghost** [comment]
@websanova It's separated in my project but not to toggle on/off, it's made to set only on an especific tool that I "added" (it's the same as line tool) but with transparency

@MaximilianoRicoTabo As I said, my project has some differences from the source code here, because I needed to change some other stuffs to work as I need. It shouldn't lose the transparency, since the object was created with that color value.

**Comment by ghost** [comment]
@websanova I didn't changed anything in the colorPicker plugin. only in the wPaint files

**Comment by ghost** [comment]
I've just dowloaded the zip from git, and changed only the setFillStyle function.

Here's the html view (don't mind about the icons, just not accessing from a root folder in my local server)
![screen shot 2014-03-10 at 11 04 39 am](https://f.cloud.github.com/assets/1001685/2374239/e6985406-a85c-11e3-8201-b22ef22ff2f4.png)

And here's the Image saved from the canvas
![transparentimage](https://f.cloud.github.com/assets/1001685/2374241/ec4f5cf0-a85c-11e3-83d2-f41451ccd070.png)

Aaaand here's the code that I changed in the file `plugins/main/src/wPaint.menu.main.js`

``` javascript
setFillStyle: function (color) {
      var hexToRgb = function(hex) {
        var b, g, r, result, shorthandRegex;
        shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
        hex = hex.replace(shorthandRegex, function(m, r, g, b) {
          return r + r + g + g + b + b;
        });
        result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
        if (result != null) {
          r = parseInt(result[1], 16);
          g = parseInt(result[2], 16);
          b = parseInt(result[3], 16);
          return result = {
            r: r,
            g: g,
            b: b,
            rgb: "" + r + ", " + g + ", " + b
          };
        } else {
          return null;
        }
      };

      var RGBColor = hexToRgb(color);
      this.options.fillStyle = "rgba(" + RGBColor.rgb + ", 0.5)";
      this.menus.all.main._setColorPickerValue('fillStyle', color);
    },
```

**Comment by MaximilianoRicoTabo** [comment]
@jsgusmao My mistake, I totally understood how you did, and It works perfect.

 In my case I also need change setStrokeStyle function. It is easily achieved doing what you pointed out.

However, the plugin seems to be so sensitive when click to draw and when I keep the mouse clicked and draw I lost the opacity. I just can get it clicking and releasing fast, but cannot keep the mouse pressed and still get the transparency.

@websanova  any thought ?

Maxi

**Comment by ghost** [comment]
@MaximilianoRicoTabo Oh, you mean the pencil tool, yeah, this doesn't get the transparency right. While you move the mouse it keeps adding "dots" constantly to the canvas (every px moved) and ends up overlapping the transparency. I've forgot to mention that.

I didn't found a good way to set transparency to the pencil tool, and since I didn't needed in it, I've decided to let it without.

**Comment by MaximilianoRicoTabo** [comment]
@jsgusmao Yes, I meant pencil tool, sorry for the poor explanation :(

**Comment by MaximilianoRicoTabo** [comment]
@jsgusmao @websanova 

Good news everyone ! I achieved pencil tool transparency mixing @jsgusmao trick to get rgba transparency and my discovering was set this.ctx.globalCompositeOperation = "destination-atop"; in _drawPencilDown function. 

By setting "destination-atop" to composite operation property we avoid pixels overlap and keep the  transparency. Hope it helps to others. Let's close this issue.

Thanks and regards

Maxi

**Comment by MaximilianoRicoTabo** [comment]
I swear this is my last comment :smile:  the composite property must be 'xor' instead of 'destination-atop', in order to keep all drawing in canvas.

**Comment by ghost** [comment]
I've tried that too, the only thing that I noticed was that the pencil will work as an "eraser tool" with a color, it doesn't place itself above the other elements it erases them filling the path with the new color. If that's not a problem in your project ^^ cheers
