### ISSUE TITLE
Toolbar position outside the drawing

### ISSUE THREAD

**Issue by luiscruz** [websanova/wPaint#8]
Hi,

It would be interesting to have an option to make the toolbar appearing outside the drawing.

Luís

**Comment by websanova** [comment]
Sure, I'll add some offset options.

**Comment by websanova** [comment]
I've added two options menuOffsetX and menuOffsetY, you can set both positive and negative values here.

**Comment by luiscruz** [comment]
Cool! Thanks :+1:
